### ISSUE TITLE
EyeTrackApp doesn't exit gracefully on linux once the tracking page is opened

### ISSUE THREAD

**Issue by othello777** [EyeTrackVR/EyeTrackVR#112]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._
If you try to close EyeTrackApp on linux, the UI will go blank but the window will hang indefinitely. If you open it directly to the settings page it will close properly, but once you have selected a tracking section it will no longer do so even if closed from the settings page.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [404] Read the [Contributing Guide and Policy](https://github.com/RedHawk989/EyeTrackVR/repo-tools/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/RedHawk989/EyeTrackVR/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/RedHawk989/EyeTrackVR/issues)
- [x] Searched the problem in [discussions](https://github.com/RedHawk989/EyeTrackVR/discussions)
- [404] Searched the problem in the [docs](https://redhawk989.github.io/EyeTrackVR/FAQ)
- [404] Searched the problem in the [chat](https://redhawk989.github.io/EyeTrackVR/contact/)
- [x] Device used (e.g., ESP32): N/A
- [x] EyeTrackVR binary firmware version number used: N/A
  - [ ] Pre-compiled
  - [x] Self-compiled
- [x] Flashing tools used: N/A
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
\> use linux 
\> go to any of the eye tracking panels
\> close the app
\> PC explodes

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._
the app should close properly and not require ^C from the terminal

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._
![image](https://github.com/EyeTrackVR/EyeTrackVR/assets/34588890/07844e9b-f7b8-4ff7-8c20-5161cf81467e)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
here's the log, including pressing ^C to close the app
```
$ poetry run python3 eyetrackapp.py 
sh: 1: color: not found
[INFO] Config Saved Successfully
[WARN] OneEuroFilter values must be a legal number.
[WARN] OneEuroFilter values must be a legal number.
[WARN] OneEuroFilter values must be a legal number.
[WARN] OneEuroFilter values must be a legal number.
[INFO] Exiting Capture thread
[INFO] Exiting Tracking thread
[INFO] Config Saved Successfully
[INFO] Exiting OSC Queue
[INFO] Exiting EyeTrackApp
^CException ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1590, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by othello777** [comment]
fixed in 7dae037 probably. after a pull the app closes fine.
